In [1]:
import numpy as np
import pandas as pd

from lightgbm.sklearn import LGBMRegressor
from sklearn.metrics import mean_squared_error

%matplotlib inline

import warnings                                  # `do not disturbe` mode
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import time
import random

# For preprocessing
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split 

# For LSTM model
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout
from keras.callbacks import EarlyStopping
from tqdm.keras import TqdmCallback

# For FOPDT model
from scipy.integrate import odeint

# For hyperopt (parameter optimization)
# ! pip install hyperopt
from hyperopt import Trials, STATUS_OK, tpe, fmin, hp

In [3]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os,cv2
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from pylab import rcParams
rcParams['figure.figsize'] = 20, 10
from sklearn.metrics import roc_curve, auc, roc_auc_score
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve,auc
from itertools import cycle
import keras
import seaborn as sns
from sklearn.model_selection import KFold
import pandas as pd
from keras.utils import np_utils
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory
from keras.models import Sequential
from keras.layers import Dense , Activation , Dropout ,Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.metrics import categorical_accuracy
from keras.models import model_from_json
from keras.callbacks import ModelCheckpoint
from keras.optimizers import *
from tensorflow.keras.layers import BatchNormalization
import os
from skimage import color
print(os.listdir(r"C:\Users\thanawin\Desktop\data\final_detect\train"))

['0', '1', '2', '3', '4', '5', '6', '7']


In [4]:
# Import libraries and packages
import matplotlib as plt
import matplotlib.pyplot as plt
plt.style.use('ggplot')
%matplotlib inline
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from keras.models import Sequential
from keras.layers.core import Dense
from tensorflow.keras.optimizers import SGD
from imutils import paths
import matplotlib.pyplot as plt
import numpy as np
import random
import pickle
import cv2
import os
import time   # time1 = time.time(); print('Time taken: {:.1f} seconds'.format(time.time() - time1))
import warnings
warnings.filterwarnings("ignore")
SEED = 42   # set random seed

In [5]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.datasets import make_classification
from keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau

In [6]:
# initialize the data and labels
print("[INFO] loading images...")
time1 = time.time()   # to measure time taken
data = []
labels = []

# grab the image paths and randomly shuffle them
imagePaths = sorted(list(paths.list_images(r'C:\Users\thanawin\Desktop\data\final_detect\train')))   # data folder with 3 categorical folders
random.seed(SEED)
random.shuffle(imagePaths)

# loop over the input images
for imagePath in imagePaths:
    # load the image, resize the image to be 32x32 pixels (ignoring aspect ratio), 
    # flatten the 32x32x3=3072 pixel image into a list, and store the image in the data list
    image = cv2.imread(imagePath)
    image = cv2.resize(image, (32, 32))
    image = color.rgb2gray(image).flatten()
    data.append(image)
 
    # extract the class label from the image path and update the labels list
    label = imagePath.split(os.path.sep)[-2]
    labels.append(label)

# scale the raw pixel intensities to the range [0, 1]

data = np.array(data, dtype="float") / 255.0
labels = np.array(labels)

print('Time taken: {:.1f} seconds'.format(time.time() - time1))   # to measure time taken
print("done")
data.shape

[INFO] loading images...
Time taken: 354.7 seconds
done


(23988, 1024)

NameError: name 'Y' is not defined

In [9]:
num_classes = 8
Y = np_utils.to_categorical(labels, num_classes)

#Shuffle the dataset
data,targets = shuffle(data,Y, random_state=42)

In [10]:
targets

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]], dtype=float32)

In [11]:
y.shape

NameError: name 'y' is not defined

In [12]:
from sklearn.preprocessing import MultiLabelBinarizer

In [13]:
X = np.load(r'C:\Users\thanawin\Desktop\data\Final_Feature_Extraction\HOG_embreded.npy') 
y = np.load(r'C:\Users\thanawin\Desktop\data\Final_Feature_Extraction\labels_HOG.npy')

In [14]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
y2 = label_encoder.fit_transform(y)

In [ ]:
y2.shape

In [15]:
num_classes = 8
Y = np_utils.to_categorical(y2, num_classes)

#Shuffle the dataset
X,y = shuffle(X,Y, random_state=42)

In [16]:
Xtrain, Xtest, ytrain, ytest = train_test_split(data,targets,test_size=0.2,shuffle=False)   

In [12]:
Xtrain

array([[2.73740869e-03, 2.76816609e-03, 1.36870434e-03, ...,
        1.44559785e-03, 1.46097655e-03, 1.86082276e-03],
       [3.01422530e-03, 2.12226067e-03, 1.36870434e-03, ...,
        2.02998847e-03, 1.93771626e-03, 1.04575163e-03],
       [1.07650903e-03, 1.07650903e-03, 7.84313725e-04, ...,
        1.83006536e-03, 1.75317186e-03, 1.72241446e-03],
       ...,
       [4.30603614e-04, 5.38254517e-04, 5.07497116e-04, ...,
        1.70703576e-03, 6.15148020e-05, 1.69165705e-04],
       [7.53556324e-04, 7.22798923e-04, 1.38408304e-03, ...,
        1.78392926e-03, 1.78392926e-03, 1.76855056e-03],
       [1.84544406e-04, 1.53787005e-04, 1.69165705e-04, ...,
        1.19953864e-03, 1.84544406e-03, 1.89158016e-03]])

In [13]:
Xtrain

array([[2.73740869e-03, 2.76816609e-03, 1.36870434e-03, ...,
        1.44559785e-03, 1.46097655e-03, 1.86082276e-03],
       [3.01422530e-03, 2.12226067e-03, 1.36870434e-03, ...,
        2.02998847e-03, 1.93771626e-03, 1.04575163e-03],
       [1.07650903e-03, 1.07650903e-03, 7.84313725e-04, ...,
        1.83006536e-03, 1.75317186e-03, 1.72241446e-03],
       ...,
       [4.30603614e-04, 5.38254517e-04, 5.07497116e-04, ...,
        1.70703576e-03, 6.15148020e-05, 1.69165705e-04],
       [7.53556324e-04, 7.22798923e-04, 1.38408304e-03, ...,
        1.78392926e-03, 1.78392926e-03, 1.76855056e-03],
       [1.84544406e-04, 1.53787005e-04, 1.69165705e-04, ...,
        1.19953864e-03, 1.84544406e-03, 1.89158016e-03]])

In [17]:
def forecast(Xtest,ytest,model):
    Yr = ytest
    Yp = model.predict(Xtest)
    Yf = ytest.copy()
    
    return Yr, Yp, Yf

In [18]:
'''from hyperopt.pyll.base import scope #quniform returns float, some parameters require int; use this to force int

space = {'rate'       : hp.uniform('rate',0.01,0.5),
         'units'      : scope.int(hp.quniform('units',10,100,5)),
         'batch_size' : scope.int(hp.quniform('batch_size',100,250,25)),
         'layers'     : scope.int(hp.quniform('layers',1,6,1))
         'kernel'
        }'''

"from hyperopt.pyll.base import scope #quniform returns float, some parameters require int; use this to force int\n\nspace = {'rate'       : hp.uniform('rate',0.01,0.5),\n         'units'      : scope.int(hp.quniform('units',10,100,5)),\n         'batch_size' : scope.int(hp.quniform('batch_size',100,250,25)),\n         'layers'     : scope.int(hp.quniform('layers',1,6,1))\n         'kernel'\n        }"

In [111]:
from hyperopt.pyll.base import scope
space = { 'choice': hp.choice('num_layers',[{'layers':'two', }]),
            'units1': hp.uniform('units1', 10,100),
            'units2': hp.uniform('units2', 10,100),
            'dropout1': hp.uniform('dropout1', .01,.5),
            'dropout2': hp.uniform('dropout2',  .01,.5),
            'learn' : hp.uniform('learn1', .001,.1),
            'momentun' : hp.uniform('momentun1', .1,.9),
            'batch_size' : scope.int(hp.quniform('batch_size',25,200,25)),
            'kernel1' : hp.choice('kernel1',['uniform', 'lecun_uniform', 'normal', 'zero', 'glorot_normal', 'glorot_uniform', 'he_normal', 'he_uniform']),
            'kernel2' : hp.choice('kernel2',['uniform', 'lecun_uniform', 'normal', 'zero', 'glorot_normal', 'glorot_uniform', 'he_normal', 'he_uniform']),
            'epochs' : 200,
            'optimizer': hp.choice('optimizer1',[SGD]),
            'activation1': hp.choice('activation1',['softmax','softsign','relu','elu','tanh','linear','swish','sigmoid','leaky_relu']),
            'activation2': hp.choice('activation2',['softmax','softsign','relu','elu','tanh','linear','swish','sigmoid','leaky_relu']),
        }

In [112]:
def f_nn(params):
    # Generate data with given window
    

    model = Sequential()
    
    print ('Params testing: ', space)
    model=keras.Sequential()
    model.add(Dense(units=int(params['units1']),kernel_initializer=params['kernel1'],
                                input_shape=(1024,),
                                kernel_regularizer=keras.regularizers.l2(0.01)))
    model.add(Dropout(params['dropout1']))
    model.add(Activation(params['activation1']))
    ##layer2
    model.add(Dense(units=int(params['units2']),kernel_initializer=params['kernel2']))
    model.add(Dropout(params['dropout2']))
    model.add(Activation(params['activation2']))
    model.add(Dense(7))
    #
    #optimizer = params['optimizer1']
    #model.compile(loss='mean_squared_error',optimizer=optimizer)
    model.compile(loss='mean_squared_error',optimizer=params['optimizer'])
    es = EarlyStopping(monitor='val_loss',mode='min',verbose=1,patience=15)
#
    result = model.fit(Xtrain, ytrain, verbose=0, validation_split=0.1,
                       batch_size=params['batch_size'],
                       epochs=200,
                       callbacks = [es,TqdmCallback(verbose=1)]
                      )
    
    #get the lowest validation loss of the training epochs
    validation_loss = np.amin(result.history['val_loss']) 
    print('Best validation loss of epoch:', validation_loss)
    #val_length = int(0.2*len(ytest))
    #Xval, yval = Xtrain[-val_length:], ytrain[-val_length:]
    
    # Evaluate forecast
    #Yr, Yp, Yf = forecast(Xval,yval,model)
    #mse = np.mean((Yr - Yf)**2)
    #print('Best forecast loss of epoch:', mse)
    
    return {'loss': validation_loss, 'status': STATUS_OK, 'model': model, 'params': params}

In [113]:
trials = Trials()
best = fmin(f_nn, space, algo=tpe.suggest, max_evals=10, trials=trials)

best_model = trials.results[np.argmin([r['loss'] for r in trials.results])]['model']
best_params = trials.results[np.argmin([r['loss'] for r in trials.results])]['params']

worst_model = trials.results[np.argmax([r['loss'] for r in trials.results])]['model']
worst_params = trials.results[np.argmax([r['loss'] for r in trials.results])]['params']

Params testing:                                       
{'choice': <hyperopt.pyll.base.Apply object at 0x0000024B419A8700>, 'units1': <hyperopt.pyll.base.Apply object at 0x0000024B419A8880>, 'units2': <hyperopt.pyll.base.Apply object at 0x0000024B419A89A0>, 'dropout1': <hyperopt.pyll.base.Apply object at 0x0000024B419A8AC0>, 'dropout2': <hyperopt.pyll.base.Apply object at 0x0000024B419FCA60>, 'learn': <hyperopt.pyll.base.Apply object at 0x0000024B419FCB80>, 'momentun': <hyperopt.pyll.base.Apply object at 0x0000024B419FCCA0>, 'batch_size': <hyperopt.pyll.base.Apply object at 0x0000024B419FCE20>, 'kernel1': <hyperopt.pyll.base.Apply object at 0x0000024B419FCF10>, 'kernel2': <hyperopt.pyll.base.Apply object at 0x0000024B419FC490>, 'epochs': 200, 'optimizer': <hyperopt.pyll.base.Apply object at 0x0000024B41930C70>, 'activation1': <hyperopt.pyll.base.Apply object at 0x0000024B41930B20>, 'activation2': <hyperopt.pyll.base.Apply object at 0x0000024B417B63A0>}
  0%|          | 0/10 [00:00<?, ?t

job exception: Could not interpret optimizer identifier: <class 'keras.optimizer_v2.gradient_descent.SGD'>



  0%|          | 0/10 [00:00<?, ?trial/s, best loss=?]


ValueError: Could not interpret optimizer identifier: <class 'keras.optimizer_v2.gradient_descent.SGD'>

In [21]:
best_model

NameError: name 'best_model' is not defined

In [ ]:
best_params

In [ ]:
worst_params

In [ ]:
best_model.get_config()

In [ ]:
best_model.summary()

In [ ]:
trials.results